//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GletredWpfEditor {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GletredWpfEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Manage  project assets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AseetBrowserToolTip {
            get {
                return ResourceManager.GetString("AseetBrowserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AssetBrowser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssetBrowser {
            get {
                return ResourceManager.GetString("AssetBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_folder_add_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_AddFolder {
            get {
                return ResourceManager.GetString("Icon_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_library_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_AssetBrowser {
            get {
                return ResourceManager.GetString("Icon_AssetBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_broom_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Broom {
            get {
                return ResourceManager.GetString("Icon_Broom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_dismiss_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Close {
            get {
                return ResourceManager.GetString("Icon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_error_circle_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Error {
            get {
                return ResourceManager.GetString("Icon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_folder_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Folder {
            get {
                return ResourceManager.GetString("Icon_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_arrow_import_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Import {
            get {
                return ResourceManager.GetString("Icon_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_info_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Info {
            get {
                return ResourceManager.GetString("Icon_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_view_desktop_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_LogViewer {
            get {
                return ResourceManager.GetString("Icon_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_full_screen_maximize_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Maximize {
            get {
                return ResourceManager.GetString("Icon_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_arrow_minimize_vertical_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Minimize {
            get {
                return ResourceManager.GetString("Icon_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_play_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Play {
            get {
                return ResourceManager.GetString("Icon_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_rename_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Rename {
            get {
                return ResourceManager.GetString("Icon_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_full_screen_minimize_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Restore {
            get {
                return ResourceManager.GetString("Icon_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_save_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Save {
            get {
                return ResourceManager.GetString("Icon_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_image_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Texture {
            get {
                return ResourceManager.GetString("Icon_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_window_arrow_up_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Viewport {
            get {
                return ResourceManager.GetString("Icon_Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_warning_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Warning {
            get {
                return ResourceManager.GetString("Icon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LevelEditor {
            get {
                return ResourceManager.GetString("LevelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can view engine and editor logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogViewerToolTip {
            get {
                return ResourceManager.GetString("LogViewerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentProject {
            get {
                return ResourceManager.GetString("RecentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the current edit file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select new project path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProjectPath {
            get {
                return ResourceManager.GetString("SelectProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Toolbar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleToolBar {
            get {
                return ResourceManager.GetString("ToggleToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewport に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Viewport {
            get {
                return ResourceManager.GetString("Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 3D drawing area on the runtime side. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewportToolTip {
            get {
                return ResourceManager.GetString("ViewportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
